import type { CurrencyCode } from '../../models/types';
import { money } from '../../utils/currency';

type Props = {
  due: number;
    paid: number;
      balance: number;

        currency: CurrencyCode;

          dueTitle?: string;
            paidTitle?: string;

              balanceStatus?: string;
                balanceColor?: 'blue' | 'red';
                };

                export default function ReportTotals({
                  due,
                    paid,
                      balance,
                        currency,

                          dueTitle = 'إجمالي المستحقات',
                            paidTitle = 'إجمالي المدفوعات',

                              balanceStatus = '',
                                balanceColor = 'blue',
                                }: Props) {
                                  const color =
                                      balanceColor === 'red'
                                            ? '#d32f2f'
                                                  : '#1565c0';

                                                    return (
                                                        <table
                                                              className="account-table"
                                                                    style={{
                                                                            marginTop: 18,
                                                                                  }}
                                                                                      >
                                                                                            <tbody>

                                                                                                    <tr className="total-row">

                                                                                                              <td>
                                                                                                                          {dueTitle}
                                                                                                                                    </td>

                                                                                                                                              <td>
                                                                                                                                                          {money(
                                                                                                                                                                        due,
                                                                                                                                                                                      currency
                                                                                                                                                                                                  )}
                                                                                                                                                                                                            </td>

                                                                                                                                                                                                                    </tr>

                                                                                                                                                                                                                            <tr className="total-row">

                                                                                                                                                                                                                                      <td>
                                                                                                                                                                                                                                                  {paidTitle}
                                                                                                                                                                                                                                                            </td>

                                                                                                                                                                                                                                                                      <td>
                                                                                                                                                                                                                                                                                  {money(
                                                                                                                                                                                                                                                                                                paid,
                                                                                                                                                                                                                                                                                                              currency
                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                    </td>

                                                                                                                                                                                                                                                                                                                                            </tr>

                                                                                                                                                                                                                                                                                                                                                    <tr className="balance-row">

                                                                                                                                                                                                                                                                                                                                                              <td>
                                                                                                                                                                                                                                                                                                                                                                          الرصيد المتبقي
                                                                                                                                                                                                                                                                                                                                                                                    </td>

                                                                                                                                                                                                                                                                                                                                                                                              <td
                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                        color,
                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 17,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {money(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Math.abs(balance),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  currency
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {balanceStatus && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {balanceStatus}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }