import { useState } from 'react';
import { useOutletContext } from 'react-router-dom';

import type { CurrencyCode, Project } from '../../models/types';

import { getCashBoxSummary } from '../../database/calculations';

import { fromYER } from '../../utils/currency';
import { printPage } from '../../utils/print';
import { sharePdfFromElement } from '../../utils/pdfShare';
import CurrencySelector from '../../components/common/CurrencySelector';
import SummaryCards from '../../components/cards/SummaryCards';

import AccountTable from '../../components/reports/AccountTable';
import ReportHeader from '../../components/reports/ReportHeader';
import ReportTotals from '../../components/reports/ReportTotals';

type Ctx = {
  project: Project;
  };

  export default function CashBox() {
    const { project } = useOutletContext<Ctx>();

      const [currency, setCurrency] =
          useState<CurrencyCode>('YER');

            const [rate, setRate] = useState(1);

              const summary = getCashBoxSummary(project);

                const convert = (v: number) =>
                    fromYER(v, currency, {
                          SAR:
                                  currency === 'SAR'
                                            ? rate
                                                      : project.exchangeRates.SAR,

                                                            USD:
                                                                    currency === 'USD'
                                                                              ? rate
                                                                                        : project.exchangeRates.USD,
                                                                                            });

                                                                                              const incomes = project.transactions.filter(
                                                                                                  t => t.type === 'owner_payment'
                                                                                                    );

                                                                                                      const expenses = project.transactions.filter(
                                                                                                          t =>
                                                                                                                t.type === 'owner_material' ||
                                                                                                                      t.type === 'owner_other_cost' ||
                                                                                                                            t.type === 'contractor_expense' ||
                                                                                                                                  t.type === 'subcontractor_payment'
                                                                                                                                    );

                                                                                                                                      return (
                                                                                                                                          <div>
                                                                                                                                                <div className="section-title-box">
                                                                                                                                                        <h2>💰 الصندوق</h2>
                                                                                                                                                              </div>

                                                                                                                                                                    <CurrencySelector
                                                                                                                                                                            currency={currency}
                                                                                                                                                                                    rates={project.exchangeRates}
                                                                                                                                                                                            rate={rate}
                                                                                                                                                                                                    onCurrency={setCurrency}
                                                                                                                                                                                                            onRate={setRate}
                                                                                                                                                                                                                  />

                                                                                                                                                                                                                        <SummaryCards
                                                                                                                                                                                                                                due={convert(summary.income)}
                                                                                                                                                                                                                                        paid={convert(summary.expense)}
                                                                                                                                                                                                                                                balance={convert(summary.displayBalance)}
                                                                                                                                                                                                                                                        currency={currency}
                                                                                                                                                                                                                                                                dueTitle="الوارد"
                                                                                                                                                                                                                                                                        paidTitle="المنصرف"
                                                                                                                                                                                                                                                                                balanceTitle="رصيد الصندوق"
                                                                                                                                                                                                                                                                                        balanceStatus={summary.status}
                                                                                                                                                                                                                                                                                                balanceColor={summary.color as 'blue' | 'red'}
                                                                                                                                                                                                                                                                                                      /><div
                                                                                                                                                                                                                                                                                                              id="print-report"
                                                                                                                                                                                                                                                                                                                      className="card print-area"
                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                    <ReportHeader
                                                                                                                                                                                                                                                                                                                                              title="كشف الصندوق"
                                                                                                                                                                                                                                                                                                                                                        project={project.name}
                                                                                                                                                                                                                                                                                                                                                                  owner={project.ownerName}
                                                                                                                                                                                                                                                                                                                                                                            currency={currency}
                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                            <AccountTable
                                                                                                                                                                                                                                                                                                                                                                                                      currency={currency}
                                                                                                                                                                                                                                                                                                                                                                                                                convert={convert}
                                                                                                                                                                                                                                                                                                                                                                                                                          hideQuantityColumns={true}
                                                                                                                                                                                                                                                                                                                                                                                                                                    showNotesColumn={true}
                                                                                                                                                                                                                                                                                                                                                                                                                                              groups={[
                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title: 'الوارد',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      rows: incomes,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title: 'المنصرف',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rows: expenses,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ReportTotals
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          due={convert(summary.income)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    paid={convert(summary.expense)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              balance={convert(summary.displayBalance)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        currency={currency}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dueTitle="الوارد"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            paidTitle="المنصرف"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      balanceStatus={summary.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                balanceColor={summary.color as 'blue' | 'red'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

<div className="row no-print">
                  <button
                              className="btn primary"
                                          onClick={() =>
                                                        printPage('print-report')
                                                                    }
                                                                              >
                                                                                          طباعة
                                                                                                    </button>

                                                                                                              <button
                                                                                                                          className="btn gray"
                                                                                                                                      onClick={() =>
                                                                                                                                                    sharePdfFromElement(
                                                                                                                                                                    'print-report',
                                                                                                                                                                                    'كشف الصندوق'
                                                                                                                                                                                                  )
                                                                                                                                                                                                              }
                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                    مشاركة PDF
                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                  }