import { useState } from 'react';
import { useOutletContext } from 'react-router-dom';

import type { CurrencyCode, Project } from '../../models/types';

import { addContractorExpense } from '../../database/transactions';
import { getContractorSummary } from '../../database/calculations';

import { fromYER } from '../../utils/currency';
import { today } from '../../utils/format';
import { printPage } from '../../utils/print';
import { sharePdfFromElement } from '../../utils/pdfShare';
import CurrencySelector from '../../components/common/CurrencySelector';
import CollapseCard from '../../components/cards/CollapseCard';
import SummaryCards from '../../components/cards/SummaryCards';

import DateInput from '../../components/forms/DateInput';
import MoneyInput from '../../components/forms/MoneyInput';
import SuggestInput from '../../components/forms/SuggestInput';
import TextAreaInput from '../../components/forms/TextAreaInput';

import AccountTable from '../../components/reports/AccountTable';
import ReportHeader from '../../components/reports/ReportHeader';
import ReportTotals from '../../components/reports/ReportTotals';

type Ctx = {
  project: Project;
  };

  export default function Contractor() {
    const { project } = useOutletContext<Ctx>();

      const [p, setP] = useState<Project>(project);
        const [currency, setCurrency] = useState<CurrencyCode>('YER');
          const [rate, setRate] = useState(1);

            const [expense, setExpense] = useState({
                title: '',
                    amount: 0,
                        currency: 'YER' as CurrencyCode,
                            date: today(),
                                notes: '',
                                  });

                                    const summary = getContractorSummary(p);

                                      const convert = (value: number) =>
                                          fromYER(value, currency, {
                                                SAR:
                                                        currency === 'SAR'
                                                                  ? rate
                                                                            : p.exchangeRates.SAR,

                                                                                  USD:
                                                                                          currency === 'USD'
                                                                                                    ? rate
                                                                                                              : p.exchangeRates.USD,
                                                                                                                  });

                                                                                                                    const revenues = p.transactions.filter(
                                                                                                                        t => t.type === 'owner_item'
                                                                                                                          );

                                                                                                                            const expenses = p.transactions.filter(
                                                                                                                                t =>
                                                                                                                                      t.type === 'contractor_expense' ||
                                                                                                                                            t.type === 'subcontractor_due'
                                                                                                                                              );

                                                                                                                                                const saveExpense = () => {
                                                                                                                                                    if (!expense.title || !expense.amount) return;

                                                                                                                                                        const updated = addContractorExpense(p, {
                                                                                                                                                              title: expense.title,
                                                                                                                                                                    amount: expense.amount,
                                                                                                                                                                          currency: expense.currency,
                                                                                                                                                                                date: expense.date,
                                                                                                                                                                                      notes: expense.notes,
                                                                                                                                                                                          });

                                                                                                                                                                                              setP(updated);

                                                                                                                                                                                                  setExpense({
                                                                                                                                                                                                        title: '',
                                                                                                                                                                                                              amount: 0,
                                                                                                                                                                                                                    currency: 'YER',
                                                                                                                                                                                                                          date: today(),
                                                                                                                                                                                                                                notes: '',
                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                  <div className="section-title-box">
                                                                                                                                                                                                                                                          <h2>👷 حساب المقاول</h2>
                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                      <CurrencySelector
                                                                                                                                                                                                                                                                              currency={currency}
                                                                                                                                                                                                                                                                                      rates={p.exchangeRates}
                                                                                                                                                                                                                                                                                              rate={rate}
                                                                                                                                                                                                                                                                                                      onCurrency={setCurrency}
                                                                                                                                                                                                                                                                                                              onRate={setRate}
                                                                                                                                                                                                                                                                                                                    /><SummaryCards
                                                                                                                                                                                                                                                                                                                            due={convert(summary.due)}
                                                                                                                                                                                                                                                                                                                                    paid={convert(summary.paid)}
                                                                                                                                                                                                                                                                                                                                            balance={convert(summary.displayBalance)}
                                                                                                                                                                                                                                                                                                                                                    currency={currency}
                                                                                                                                                                                                                                                                                                                                                            dueTitle="إجمالي المستحقات"
                                                                                                                                                                                                                                                                                                                                                                    paidTitle="إجمالي المدفوعات"
                                                                                                                                                                                                                                                                                                                                                                            balanceTitle="الرصيد المتبقي"
                                                                                                                                                                                                                                                                                                                                                                                    balanceStatus={summary.status}
                                                                                                                                                                                                                                                                                                                                                                                            balanceColor={summary.color as 'blue' | 'red'}
                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                        <CollapseCard title="إضافة مصروف">
                                                                                                                                                                                                                                                                                                                                                                                                                <SuggestInput
                                                                                                                                                                                                                                                                                                                                                                                                                          label="البيان"
                                                                                                                                                                                                                                                                                                                                                                                                                                    value={expense.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                              typeKey="expenseTypes"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(v) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setExpense({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ...expense,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title: v,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <MoneyInput
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                label="المبلغ"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          amount={expense.amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    currency={expense.currency}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onAmount={(v) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setExpense({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ...expense,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      amount: v,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onCurrency={(v) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setExpense({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ...expense,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              currency: v,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <DateInput
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              label="التاريخ"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={expense.date}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(v) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setExpense({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...expense,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          date: v,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <TextAreaInput
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          label="ملاحظات"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={expense.notes}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(v) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setExpense({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ...expense,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      notes: v,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="btn primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={saveExpense}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  حفظ المصروف
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </CollapseCard><div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        id="print-report"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="card print-area"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ReportHeader
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title="كشف حساب المقاول"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  project={p.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            owner={p.ownerName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      currency={currency}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <AccountTable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                currency={currency}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          convert={convert}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    hideQuantityColumns={true}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              showNotesColumn={true}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        groups={[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  title: 'مستحقات المقاول',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rows: revenues,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title: 'مصروفات المقاول ومقاولي الباطن',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rows: expenses,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ReportTotals
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    due={convert(summary.due)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              paid={convert(summary.paid)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        balance={convert(summary.displayBalance)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  currency={currency}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dueTitle="إجمالي المستحقات"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      paidTitle="إجمالي المدفوعات"

balanceStatus={summary.status}
          balanceColor={summary.color as 'blue' | 'red'}
                  />                                    /

                                              <div className="row no-print">
                                                        <button
                                                                    className="btn primary"
                                                                                onClick={() =>
                                                                                              printPage('print-report')
                                                                                                          }
                                                                                                                    >
                                                                                                                                طباعة
                                                                                                                                          </button>

                                                                                                                                                    <button
                                                                                                                                                                className="btn gray"
                                                                                                                                                                            onClick={() =>
                                                                                                                                                                                          sharePdfFromElement(
                                                                                                                                                                                                          'print-report',
                                                                                                                                                                                                                          'كشف حساب المقاول'
                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                          مشاركة PDF
                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                        }