import { Link } from 'react-router-dom';
import type { Project } from '../../models/types';

type Props = {
  project: Project;
    onEdit: (project: Project) => void;
      onDelete: (id: string) => void;
      };

      export default function ProjectCard({
        project,
          onEdit,
            onDelete,
            }: Props) {
              return (
                  <div className="project-card">
                        <div className="project-card-header">
                                <div>
                                          <h2
                                                      style={{
                                                                    margin: 0,
                                                                                  fontWeight: 700,
                                                                                              }}
                                                                                                        >
                                                                                                                    {project.name}
                                                                                                                              </h2>

                                                                                                                                        <div
                                                                                                                                                    style={{
                                                                                                                                                                  marginTop: 6,
                                                                                                                                                                                fontSize: '1rem',
                                                                                                                                                                                              fontWeight: 700,
                                                                                                                                                                                                            color: '#1f2937',
                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                              {project.ownerName}
                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                            marginTop: 6,
                                                                                                                                                                                                                                                                                                          color: '#6b7280',
                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                            {project.location}
                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                          marginTop: 6,
                                                                                                                                                                                                                                                                                                                                                                                                        color: '#6b7280',
                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                          الحالة: {project.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="project-card-actions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="btn primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    to={`/project/${project.id}/owner`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      فتح المشروع
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="btn gray"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => onEdit(project)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            تعديل المشروع
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="btn danger"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => onDelete(project.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  حذف المشروع
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }