import { useState } from 'react';

import type {
  Project,
    ProjectStatus,
    } from '../../models/types';

    import { PROJECT_STATUS } from '../../utils/constants';

    type Props = {
      initial?: Partial<Project>;
        onSave: (data: Partial<Project>) => void;
          onCancel: () => void;
          };

          export default function ProjectForm({
            initial = {},
              onSave,
                onCancel,
                }: Props) {
                  const [form, setForm] = useState({
                      name: initial.name || '',
                          ownerName: initial.ownerName || '',
                              ownerPhone: initial.ownerPhone || '',
                                  location: initial.location || '',
                                      area: initial.area || '',
                                          startDate: initial.startDate || '',
                                              status: (initial.status || 'active') as ProjectStatus,
                                                  notes: initial.notes || '',
                                                    });

                                                      const change = (
                                                          key: keyof typeof form,
                                                              value: string
                                                                ) => {
                                                                    setForm({
                                                                          ...form,
                                                                                [key]: value,
                                                                                    });
                                                                                      };

                                                                                        const save = () => {
                                                                                            if (!form.name.trim()) {
                                                                                                  alert('أدخل اسم المشروع');
                                                                                                        return;
                                                                                                            }

                                                                                                                onSave(form);
                                                                                                                  };

                                                                                                                    return (
                                                                                                                        <div className="card">
                                                                                                                              <h3>
                                                                                                                                      {initial.id ? 'تعديل المشروع' : 'إضافة مشروع'}
                                                                                                                                            </h3>

                                                                                                                                                  <label className="field">
                                                                                                                                                          <span>اسم المشروع</span>
                                                                                                                                                                  <input
                                                                                                                                                                            value={form.name}
                                                                                                                                                                                      onChange={(e) =>
                                                                                                                                                                                                  change('name', e.target.value)
                                                                                                                                                                                                            }
                                                                                                                                                                                                                    />
                                                                                                                                                                                                                          </label>

                                                                                                                                                                                                                                <label className="field">
                                                                                                                                                                                                                                        <span>اسم المالك</span>
                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                          value={form.ownerName}
                                                                                                                                                                                                                                                                    onChange={(e) =>
                                                                                                                                                                                                                                                                                change('ownerName', e.target.value)
                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                        </label>

                                                                                                                                                                                                                                                                                                              <label className="field">
                                                                                                                                                                                                                                                                                                                      <span>رقم الهاتف</span>
                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                        inputMode="tel"
                                                                                                                                                                                                                                                                                                                                                  value={form.ownerPhone}
                                                                                                                                                                                                                                                                                                                                                            onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                        change('ownerPhone', e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                </label>

                                                                                                                                                                                                                                                                                                                                                                                                      <label className="field">
                                                                                                                                                                                                                                                                                                                                                                                                              <span>الموقع</span>
                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                value={form.location}
                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      change('location', e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>المساحة</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              inputMode="decimal"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={form.area}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              change('area', e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>تاريخ البداية</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="date"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={form.startDate}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      change('startDate', e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>حالة المشروع</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={form.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    change(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'status',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                e.target.value as ProjectStatus
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {PROJECT_STATUS.map((s) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={s.value}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={s.value}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {s.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>ملاحظات</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={form.notes}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    change('notes', e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="btn primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={save}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                حفظ
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="btn gray"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={onCancel}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      إلغاء
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }