import { useNavigate } from 'react-router-dom';

type Props = {
  title: string;
    subtitle?: string;
      backTo?: string;
      };

      export default function PageHeader({
        title,
          subtitle,
            backTo,
            }: Props) {
              const navigate = useNavigate();

                return (
                    <div
                          className="page-header"
                                style={{
                                        display: 'flex',
                                                alignItems: 'center',
                                                        gap: 14,
                                                                marginBottom: 18,
                                                                      }}
                                                                          >
                                                                                <button
                                                                                        onClick={() =>
                                                                                                  backTo
                                                                                                              ? navigate(backTo)
                                                                                                                          : navigate(-1)
                                                                                                                                  }
                                                                                                                                          style={{
                                                                                                                                                    width: 52,
                                                                                                                                                              height: 52,
                                                                                                                                                                        borderRadius: '50%',
                                                                                                                                                                                  border: 'none',
                                                                                                                                                                                            cursor: 'pointer',
                                                                                                                                                                                                      background: '#1976d2',
                                                                                                                                                                                                                color: '#fff',
                                                                                                                                                                                                                          fontSize: 28,
                                                                                                                                                                                                                                    fontWeight: 700,
                                                                                                                                                                                                                                              boxShadow:
                                                                                                                                                                                                                                                          '0 4px 12px rgba(0,0,0,.25)',
                                                                                                                                                                                                                                                                    flexShrink: 0,
                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                          ←
                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                        flex: 1,
                                                                                                                                                                                                                                                                                                                                  borderRight: '5px solid #0B3BB5',
                                                                                                                                                                                                                                                                                                                                            background: 'rgba(11,59,181,0.04)',
                                                                                                                                                                                                                                                                                                                                                      borderRadius: 12,
                                                                                                                                                                                                                                                                                                                                                                padding: '10px 14px',
                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                      <h1
                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                            margin: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 22,
                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: 800,
                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#0B3BB5',
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {subtitle && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#374151',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: 600,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {subtitle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }