import type {
    Project,
      SummaryResult,
        CashSummaryResult,
        } from '../models/types';

        const sum = (
          rows: { amountYER?: number }[]
          ) =>
            rows.reduce(
                (total, row) =>
                      total + Number(row.amountYER || 0),
                          0
                            );

                            const isRedStatus = (status: string) =>
                              status === 'عليه' ||
                                status === 'عليهم' ||
                                  status === 'عجز';

                                  const result = (
                                    due: number,
                                      paid: number,
                                        positiveStatus: string,
                                          negativeStatus: string
                                          ): SummaryResult => {
                                            const balance = due - paid;

                                              const status =
                                                  balance >= 0
                                                        ? positiveStatus
                                                              : negativeStatus;

                                                                return {
                                                                    due,
                                                                        paid,
                                                                            balance,
                                                                                status,
                                                                                    color: isRedStatus(status)
                                                                                          ? 'red'
                                                                                                : 'blue',
                                                                                                    displayBalance:
                                                                                                          Math.abs(balance),
                                                                                                            };
                                                                                                            };

                                                                                                            export function getOwnerSummary(
                                                                                                              project: Project
                                                                                                              ): SummaryResult {
                                                                                                                const due = sum(
                                                                                                                    project.transactions.filter(
                                                                                                                          t =>
                                                                                                                                  t.type === 'owner_item' ||
                                                                                                                                          t.type === 'owner_material' ||
                                                                                                                                                  t.type === 'owner_other_cost'
                                                                                                                                                      )
                                                                                                                                                        );

                                                                                                                                                          const paid = sum(
                                                                                                                                                              project.transactions.filter(
                                                                                                                                                                    t => t.type === 'owner_payment'
                                                                                                                                                                        )
                                                                                                                                                                          );

                                                                                                                                                                            return result(
                                                                                                                                                                                due,
                                                                                                                                                                                    paid,
                                                                                                                                                                                        'عليه',
                                                                                                                                                                                            'له'
                                                                                                                                                                                              );
                                                                                                                                                                                              }

                                                                                                                                                                                              export function getContractorSummary(
                                                                                                                                                                                                project: Project
                                                                                                                                                                                                ): SummaryResult {
                                                                                                                                                                                                  const due = sum(
                                                                                                                                                                                                      project.transactions.filter(
                                                                                                                                                                                                            t => t.type === 'owner_item'
                                                                                                                                                                                                                )
                                                                                                                                                                                                                  );

                                                                                                                                                                                                                    const paid = sum(
                                                                                                                                                                                                                        project.transactions.filter(
                                                                                                                                                                                                                              t =>
                                                                                                                                                                                                                                      t.type === 'contractor_expense' ||
                                                                                                                                                                                                                                              t.type === 'subcontractor_due'
                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                      return result(
                                                                                                                                                                                                                                                          due,
                                                                                                                                                                                                                                                              paid,
                                                                                                                                                                                                                                                                  'له',
                                                                                                                                                                                                                                                                      'عليه'
                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                        export function getSubcontractorSummary(
                                                                                                                                                                                                                                                                          project: Project,
                                                                                                                                                                                                                                                                            subcontractorId: string
                                                                                                                                                                                                                                                                            ): SummaryResult {
                                                                                                                                                                                                                                                                              const due = sum(
                                                                                                                                                                                                                                                                                  project.transactions.filter(
                                                                                                                                                                                                                                                                                        t =>
                                                                                                                                                                                                                                                                                                t.type === 'subcontractor_due' &&
                                                                                                                                                                                                                                                                                                        t.relatedId === subcontractorId
                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                const paid = sum(
                                                                                                                                                                                                                                                                                                                    project.transactions.filter(
                                                                                                                                                                                                                                                                                                                          t =>
                                                                                                                                                                                                                                                                                                                                  t.type ===
                                                                                                                                                                                                                                                                                                                                            'subcontractor_payment' &&
                                                                                                                                                                                                                                                                                                                                                    t.relatedId === subcontractorId
                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                                                            return result(
                                                                                                                                                                                                                                                                                                                                                                due,
                                                                                                                                                                                                                                                                                                                                                                    paid,
                                                                                                                                                                                                                                                                                                                                                                        'له',
                                                                                                                                                                                                                                                                                                                                                                            'عليه'
                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                              export function getSubcontractorsSummary(
                                                                                                                                                                                                                                                                                                                                                                                project: Project
                                                                                                                                                                                                                                                                                                                                                                                ): SummaryResult {
                                                                                                                                                                                                                                                                                                                                                                                  const due = sum(
                                                                                                                                                                                                                                                                                                                                                                                      project.transactions.filter(
                                                                                                                                                                                                                                                                                                                                                                                            t => t.type === 'subcontractor_due'
                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                    const paid = sum(
                                                                                                                                                                                                                                                                                                                                                                                                        project.transactions.filter(
                                                                                                                                                                                                                                                                                                                                                                                                              t => t.type === 'subcontractor_payment'
                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                      return result(
                                                                                                                                                                                                                                                                                                                                                                                                                          due,
                                                                                                                                                                                                                                                                                                                                                                                                                              paid,
                                                                                                                                                                                                                                                                                                                                                                                                                                  'لهم',
                                                                                                                                                                                                                                                                                                                                                                                                                                      'عليهم'
                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                        export function getCashBoxSummary(
                                                                                                                                                                                                                                                                                                                                                                                                                                          project: Project
                                                                                                                                                                                                                                                                                                                                                                                                                                          ): CashSummaryResult {
                                                                                                                                                                                                                                                                                                                                                                                                                                            const income = sum(
                                                                                                                                                                                                                                                                                                                                                                                                                                                project.transactions.filter(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      t => t.type === 'owner_payment'
                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                              const expense = sum(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  project.transactions.filter(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        t =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                t.type === 'owner_material' ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        t.type === 'owner_other_cost' ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                t.type === 'contractor_expense' ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        t.type === 'subcontractor_payment'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const balance = income - expense;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const status =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      balance >= 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? 'متوفر'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : 'عجز';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        income,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expense,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                balance,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: isRedStatus(status)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? 'red'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : 'blue',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        displayBalance:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Math.abs(balance),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export function getProjectSummary(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  project: Project
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        owner: getOwnerSummary(project),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            contractor: getContractorSummary(project),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                subcontractors:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      getSubcontractorsSummary(project),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cash: getCashBoxSummary(project),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
