import { Link } from 'react-router-dom';
import { useState } from 'react';

import {
  getTrash,
    restoreProject,
      removeProjectForever,
        emptyTrash,
        } from '../../database/database';

        import type { Project } from '../../models/types';

        import AppCard from '../../components/cards/AppCard';

        export default function Trash() {
          const [items, setItems] =
              useState<Project[]>(getTrash());

                const refresh = () =>
                    setItems(getTrash());

                      const restore = (id: string) => {
                          restoreProject(id);
                              refresh();
                                };

                                  const remove = (id: string) => {
                                      if (
                                            !confirm(
                                                    'هل أنت متأكد من حذف هذا المشروع نهائيًا؟ لا يمكن استعادته بعد ذلك.'
                                                          )
                                                              ) {
                                                                    return;
                                                                        }

                                                                            removeProjectForever(id);
                                                                                refresh();
                                                                                  };

                                                                                    const clear = () => {
                                                                                        if (
                                                                                              !confirm(
                                                                                                      'هل أنت متأكد من حذف جميع المشاريع نهائيًا؟ لا يمكن استعادتها بعد ذلك.'
                                                                                                            )
                                                                                                                ) {
                                                                                                                      return;
                                                                                                                          }

                                                                                                                              emptyTrash();
                                                                                                                                  refresh();
                                                                                                                                    };

                                                                                                                                      return (
                                                                                                                                          <div className="home-page">
                                                                                                                                                <div className="home-container">
                                                                                                                                                        <div className="home-top-actions no-print">
                                                                                                                                                                  <Link
                                                                                                                                                                              to="/"
                                                                                                                                                                                          className="trash-link"
                                                                                                                                                                                                    >
                                                                                                                                                                                                                ← رجوع
                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                          <AppCard title="🗑️ سلة المحذوفات">
                                                                                                                                                                                                                                                    {items.length > 0 && (
                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                              marginBottom: 16,
                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                      className="btn danger"
                                                                                                                                                                                                                                                                                                                                                                      onClick={clear}
                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                    حذف الكل نهائيًا
                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                  {!items.length && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="empty-state">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            لا توجد مشاريع محذوفة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {items.map(project => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={project.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="card"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>{project.name}</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <b>رقم المشروع:</b>{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {project.code}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <b>المالك:</b>{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {project.ownerName || '-'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <b>الموقع:</b>{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {project.location || '-'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="btn primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        restore(project.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            استعادة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="btn danger"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    remove(project.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        حذف نهائي
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </AppCard>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }