import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import Activation from './pages/Activation';

import { getLicenseState } from './utils/license';
import {
  BrowserRouter,
    Navigate,
      Route,
        Routes,
        } from 'react-router-dom';

        import Home from './pages/Home/Home';
        import Trash from './pages/Trash/Trash';
        import CurrencySettings from './pages/CurrencySettings';
        import AppProfile from './pages/AppProfile/AppProfile';

        import ProjectLayout from './pages/Project/ProjectLayout';
        import Owner from './pages/Project/Owner';
        import Contractor from './pages/Project/Contractor';
        import SubcontractorsList from './pages/Project/SubcontractorsList';
        import SubcontractorDetail from './pages/Project/SubcontractorDetail';
        import CashBox from './pages/Project/CashBox';
        import Documents from './pages/Project/Documents';
        import Reports from './pages/Project/Reports';
        import Settings from './pages/Project/Settings';

        type SecuritySettings = {
          passwordEnabled: boolean;
            password: string;
              autoLock: string;
                hideBalances: boolean;
                  notes: string;
                  };

                  const SECURITY_KEY = 'dftr-security';

                  const defaultSecurity: SecuritySettings = {
                    passwordEnabled: false,
                      password: '',
                        autoLock: 'off',
                          hideBalances: false,
                            notes: '',
                            };

                            const getSecurity = (): SecuritySettings => {
                              try {
                                  const saved =
                                        localStorage.getItem(SECURITY_KEY);

                                            if (!saved) {
                                                  return defaultSecurity;
                                                      }

                                                          return {
                                                                ...defaultSecurity,
                                                                      ...JSON.parse(saved),
                                                                          };
                                                                            } catch {
                                                                                return defaultSecurity;
                                                                                  }
                                                                                  };

                                                                                  function AppLock({
                                                                                    children,
                                                                                    }: {
                                                                                      children: ReactNode;
                                                                                      }) {
                                                                                        const security = getSecurity();

                                                                                          const [password, setPassword] = useState('');

                                                                                            const [unlocked, setUnlocked] = useState(
                                                                                                !security.passwordEnabled ||
                                                                                                      !security.password
                                                                                                        );

                                                                                                          const login = () => {
                                                                                                              if (password === security.password) {
                                                                                                                    setUnlocked(true);
                                                                                                                          return;
                                                                                                                              }

                                                                                                                                  alert('كلمة المرور غير صحيحة');
                                                                                                                                    };

                                                                                                                                      if (unlocked) {
                                                                                                                                          return <>{children}</>;
                                                                                                                                            }

                                                                                                                                              return (
                                                                                                                                                  <div className="lock-page">
                                                                                                                                                        <div className="lock-card">
                                                                                                                                                                <h2>🔒 قفل التطبيق</h2>

                                                                                                                                                                        <p>أدخل كلمة المرور للدخول</p>

                                                                                                                                                                                <input
                                                                                                                                                                                          type="password"
                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                              autoFocus
                                                                                                                                                                                                                        placeholder="كلمة المرور"
                                                                                                                                                                                                                                  onChange={(e) =>
                                                                                                                                                                                                                                              setPassword(e.target.value)
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                  onKeyDown={(e) => {
                                                                                                                                                                                                                                                                              if (e.key === 'Enter') {
                                                                                                                                                                                                                                                                                            login();
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                            className="btn primary"
                                                                                                                                                                                                                                                                                                                                                      onClick={login}
                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                        دخول
                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                            }


function LicenseGate({
    children,
    }: {
      children: ReactNode;
      }) {
        const [checking, setChecking] =
            useState(true);

              const [allowed, setAllowed] =
                  useState(false);

                    useEffect(() => {
                        getLicenseState().then((state) => {
                              const canEnter =
                                      state.activated ||
                                              !state.trialExpired;

                                                    setAllowed(canEnter);
                                                          setChecking(false);
                                                              });
                                                                }, []);

                                                                  if (checking) {
                                                                      return (
                                                                            <div className="activation-page">
                                                                                    <div className="activation-card">
                                                                                              جاري التحقق من الترخيص...
                                                                                                      </div>
                                                                                                            </div>
                                                                                                                );
                                                                                                                  }

                                                                                                                    if (!allowed) {
                                                                                                                        return <Activation />;
                                                                                                                          }

                                                                                                                            return <>{children}</>;
                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                         export default function App() {
                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                  <BrowserRouter>
                                                                                                                                                                 
                                                                                                                 <LicenseGate>                                                                                                                                                                                                                                                                                     <AppLock>
                                                                                                                                                                                                                                                                                                                                                                                                          <Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                          <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                      path="/"
                                                                                                                                                                                                                                                                                                                                                                                                                                                  element={<Home />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  path="/trash"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              element={<Trash />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              path="/currency"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          element={<CurrencySettings />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          path="/app-profile"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      element={<AppProfile />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      path="/project/:id"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  element={<ProjectLayout />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      index
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Navigate
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      to="owner"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        replace
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            path="owner"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          element={<Owner />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                path="contractor"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              element={<Contractor />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    path="subcontractors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  element={<SubcontractorsList />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        path="subcontractor/:subcontractorId"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      element={<SubcontractorDetail />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            path="cashbox"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          element={<CashBox />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                path="documents"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              element={<Documents />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    path="reports"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  element={<Reports />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        path="settings"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      element={<Settings />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Route>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  path="*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Navigate
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            to="/"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            replace
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Routes>
</AppLock>
    </LicenseGate>
      </BrowserRouter>
      );                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }